---
title: "Resources"
description: |
  An opinionated list of guides or tutorials for Shiny and helping packages
output: 
  distill::distill_article:
    toc: true
    toc_float: true
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Module Material

Script templates and intermediate scripts prepared for this module can be forked or downloaded from [github](https://github.com/psrc/intro-shiny). 

# Shiny

**[Shiny Gallery's Shiny Demo](https://shiny.rstudio.com/gallery/#demos)**: interactive examples of various Shiny features (individual widgets, layout styles, and reactivity). The source code is displayed as you interact with the examples. It's a great way to learn! 

**[Official Cheatsheet](https://github.com/rstudio/cheatsheets/blob/master/shiny.pdf)**: A two-pager of Shiny utilities. 

**[Mastering Shiny Book](https://mastering-shiny.org/index.html)**: A book (in progress) by Hadley Wickham. See the *Getting Started* section. For those who use the tidyverse, it also includes a section on the latest version of *tidy evaluation*--essential for programming with packages like dplyr or ggplot2.

**[Datacamp: Building Web Applications with Shiny in R](https://learn.datacamp.com/courses/building-web-applications-with-shiny-in-r)**: 4 hours of Shiny instruction and hands-on activity. Go more in-depth with reactivity and learn how to use the `isolate()` function. Courses on Shinydashboard and Flexdashboard are also available via Datacamp.


# Visualization Packages

## DT

[DT](https://rstudio.github.io/DT/) is an R adaptation of the JavaScript library [DataTables](https://datatables.net/). It generates an HTML table with advanced features such as filtering, pagination, sorting, and many others.

### Other htmlwidgets

DT like Plotly and Leaflet are part of the [htmlwidgets family](https://www.htmlwidgets.org/showcase_leaflet.html), an effort to bring the best of JavaScript visualization into R to create interactive visualizations. `htmlwidgets` itself is a package for developers to bind various JS packages to R.

## Reactable

Another interactive table package. On the surface, basic use of [reactable](https://glin.github.io/reactable/) might not be that different than DT, but the ability to create expandable rows and nested tables, and the conditional styling examples really makes this package stand out.

To see a Shiny app with a reactable table in the wild, see [this reactable example](https://christy-lam.shinyapps.io/ofm-wa-estimates/), code is available [here](https://github.com/cyyllam/ofm-wa-estimates).

